Models/Snippet.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using MongoDB.Driver;

namespace dotnetSnipz.Models
{
    public class Snippet
    {
        public Guid Id { get; set; }

        [Required]
        public string Title { get; set; }

		
		public string Desc { get; set; }


		[Required]
        public string Code { get; set; }

        [Required]
        public string Lang { get; set; }

        public static explicit operator UpdateDefinition<object>(Snippet v)
        {
            throw new NotImplementedException();
        }
    }
}

Controllers/SnippetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Driver;
using dotnetSnipz.Models;
using System.Diagnostics.Contracts;

namespace dotnetSnipz.Controllers
{
    public class SnippetController : Controller
    {
        public IActionResult Index()
        {
            MongoDBContext dbContext = new MongoDBContext();

            List<Snippet> snippetList = dbContext.Snippets.Find(m => true).ToList();

            return View(snippetList);
        }

        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            MongoDBContext dbContext = new MongoDBContext();
            var entity = dbContext.Snippets.Find(m => m.Id == id).FirstOrDefault();

            return View(entity);
        }

		[HttpGet]
		public IActionResult Detail(Guid id)
		{
			MongoDBContext dbContext = new MongoDBContext();
			var entity = dbContext.Snippets.Find(m => m.Id == id).FirstOrDefault();



			return View(entity);
		}

		[HttpGet]
		public IActionResult Search(string lang)
		{;
            MongoDBContext dbContext = new MongoDBContext();
            var resultsList = dbContext.Snippets.Find(m=> m.Lang == lang);

			return View(resultsList);
		}

		[HttpPost]
        public IActionResult Edit(Snippet entity)
        {
            MongoDBContext dbContext = new MongoDBContext();

            //you can use the UpdateOne to get higher performance if you need.
            dbContext.Snippets.ReplaceOne(m => m.Id == entity.Id, entity);

            return View(entity);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Snippet entity)
        {
            MongoDBContext dbContext = new MongoDBContext();

            entity.Id = Guid.NewGuid();

            dbContext.Snippets.InsertOne(entity);

            return Redirect("/");
        }

        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            MongoDBContext dbContext = new MongoDBContext();

            dbContext.Snippets.DeleteOne(m => m.Id == id);

            return Redirect("/");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - dotnetSnipz</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Snippet" asp-action="Index" class="navbar-brand">dotnetSnipz</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Snippet" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Snippet" asp-action="Add">New Snippet</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - dotnetSnipz</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

Views/Snippet/Add.cshtml
@model dotnetSnipz.Models.Snippet

@{ ViewBag.Title = "Add A New Code Snippet";}

<h2>@ViewBag.Title</h2>

<form asp-controller="Snippet" asp-action="Add" method="post" class="form-horizontal" role="form">
    <div class="form-horizontal">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Title" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Desc" class="col-md-2 control-label">Description (Optional)</label>
            <div class="col-md-10">
                <input asp-for="Desc" class="form-control" />
                <span asp-validation-for="Desc" class="text-danger"></span>
            </div>
        </div>		
        <div class="form-group">
            <label asp-for="Code" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Lang" class="col-md-2 control-label">Language</label>
            <div class="col-md-10">
                <input asp-for="Lang" class="form-control" />
                <span asp-validation-for="Lang" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

Views/Snippet/Detail.cshtml
@model dotnetSnipz.Models.Snippet

@{ViewBag.Title = @Model.Title;}

<h1>@ViewBag.Title</h1>

<div>
	<h6>@Model.Desc</h6>
	<p>Copy the code from the box below and Paste into your preferred text editor or IDE.</p>
	<pre>@Model.Code</pre>
	<p><a href="Snippet/Search/@Model.Lang">@Model.Lang</a></p>
</div>

Views/Snippet/Edit.cshtml
@model dotnetSnipz.Models.Snippet

@{ ViewBag.Title = "Edit Code Snippet";}

<h2>@ViewBag.Title</h2>

<form asp-controller="Snippet" asp-action="Edit" method="post" class="form-horizontal" role="form">
    <div class="form-horizontal">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Id" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Id" class="form-control" readonly="readonly" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Title" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
        </div>
		        <div class="form-group">
            <label asp-for="Desc" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Desc" class="form-control" />
                <span asp-validation-for="Desc" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Code" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Lang" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Lang" class="form-control" />
                <span asp-validation-for="Lang" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

Views/Snippet/Index.cshtml
@model IEnumerable<dotnetSnipz.Models.Snippet>

@{ ViewBag.Title = "My Code Snippets";}

<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th>Title</th>
		<th>Description</th>
<!--        <th>Code</th>-->
		<th>Language</th>
        <th>Edit/Delete</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a href="Snippet/Detail/@item.Id">
                    @item.Title
                </a>
            </td>
            <td>
                <a href="Snippet/Detail/@item.Id">
                    @item.Desc
                </a>
            </td>		
<!--            <td>
                <a href="Snippet/Detail/@item.Id">
                    <pre>@item.Code</pre>
                </a>
            </td>-->
		    <td>
                <a href="Snippet/Detail/@item.Id">
                    @item.Lang
                </a>
            </td>
            <td>
                <a href="Snippet/Edit/@item.Id">Edit</a> | <a href="Snippet/Delete/@item.Id">Delete</a>
            </td>
        </tr>
    }
</table>

Views/Snippet/Search.cshtml


@{ ViewBag.Title = @Model.Lang "Snippets";}

<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th>Title</th>
		<th>Description</th>
<!--        <th>Code</th>-->
		<th>Language</th>
        <th>Edit/Delete</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a href="Snippet/Detail/@item.Id">
                    @item.Title
                </a>
            </td>
            <td>
                <a href="Snippet/Detail/@item.Id">
                    @item.Desc
                </a>
            </td>		
<!--            <td>
                <a href="Snippet/Detail/@item.Id">
                    <pre>@item.Code</pre>
                </a>
            </td>-->
		    <td>
                <a href="Snippet/Detail/@item.Id">
                    @item.Lang
                </a>
            </td>
            <td>
                <a href="Snippet/Edit/@item.Id">Edit</a> | <a href="Snippet/Delete/@item.Id">Delete</a>
            </td>
        </tr>
    }
</table>